In [3]:
"1. Import numpy, and explore their functionalities. "
import numpy as np 
arr1 = np.array([10,20,30,40,50]) 
print(arr1)
print(type(arr1)) 

#1-D Arrays
arr = np.array([1, 2, 3, 4, 5])
print("1-D Array")
print(arr)
print(arr[0])
      
#2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print("2-D Array")
print(arr) 
print(arr[1][1]) 
print(arr[1])

#Dimension
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Dimension")
print(arr.ndim) 
#Size of each element (in bytes) 
print("#Size of each element in bytes")
print(arr.itemsize) 
#Datatype
print("Datatype")
print(arr.dtype) 
#Size and Shape
print("Size and Shape")
print(arr.size) 
print(arr.shape) 
#Reshape
print("Reshape")
a=arr.reshape(3,2)
print(a) 
#Slicing
print("Slicing")
print(arr[0:,2]) 
#Min/Max/Sum
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print("min is ",arr.min())
print("max is ",arr.max())
print("sum is ",arr.sum())

[10 20 30 40 50]
<class 'numpy.ndarray'>
1-D Array
[1 2 3 4 5]
1
2-D Array
[[1 2 3]
 [4 5 6]]
5
[4 5 6]
Dimension
2
#Size of each element in bytes
4
Datatype
int32
Size and Shape
6
(2, 3)
Reshape
[[1 2]
 [3 4]
 [5 6]]
Slicing
[3 6]
min is  1
max is  6
sum is  21


In [7]:
"3. Write a program for slicing arrays using numpy ."
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[1:5]) 
print(arr[4:]) 
print(arr[:4]) 
print(arr[-3:-1]) 
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [9]:
"4. Write a program for Math operations on array using numpy. "
#Square Root and Standard Deviation
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sqrt(arr))
print(np.std(arr))

#Addition, subtraction, multiplication and division of the two matrices
arr1=np.array([[5,6,7],[2,3,4]])
arr2=np.array([[5,6,7],[4,3,2]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

#Vertical and Horizontal Stacking
arr1=np.array([[1,3,2],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print("vstack:",np.vstack((arr1,arr2)))
print("hstack:",np.hstack((arr1,arr2)))

#Ravel:
arr=np.array([[1,5,7],[6,7,1]])
print(np.ravel(arr))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933
[[10 12 14]
 [ 6  6  6]]
[[ 0  0  0]
 [-2  0  2]]
[[25 36 49]
 [ 8  9  8]]
[[1.  1.  1. ]
 [0.5 1.  2. ]]
vstack: [[ 1  3  2]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
hstack: [[ 1  3  2  7  8  9]
 [ 4  5  6 10 11 12]]
[1 5 7 6 7 1]


In [11]:
"5. Write a program for searching ."
import numpy as np
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
i = np.where(arr == 30)
print(i)

(array([2], dtype=int64),)


In [15]:
"6. Write a program for sorting."
import numpy as np  
arr=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
sort_arr=np.sort(arr)  
print(sort_arr)

[[ 1  2  3  4]
 [ 1  9 13 61]
 [22 24 43 88]]
